### ISSUE TITLE
Rewrite Drivetrain

### ISSUE THREAD

**Issue by mananshah99** [HarkerRobo/robocode2015#1]
Drivetrain
- Needs talons
- Robotmap Ports
- Gyro

Drive method which should look similar to last year and `getCurrentHeading` which gets gyro angle
Be sure to reset gyro in constructor.

**Comment by Andrew-Tierno** [comment]
Also add an "initialize" method to Drivetrain and invoke it from robotInit

**Comment by Andrew-Tierno** [comment]
Also add an instance of the RobotDrive class with the four talons as inputs

**Comment by Andrew-Tierno** [comment]
Fixed as of most recent commit
